In [42]:
import torch

# Tensors

## Definition

- What is it ? A tensor is a multidimensional data structure provided by torch.

- What is it used for ? Tensors are used to store data (for example, images and vectors of features). It is the input and output of torch neural networks and neural networks parameters are stored in tensors.

- What are the attributes of a Tensor ? 
    - size : describe the length of each dimension
    - dtype : the type of the scalars strored in the tensor (float,int, complex and more)
    - device : the device where the tensor is stored in memory (typically CPU or GPU)
    - dim : the number of dimensions of the tensor

- Why use tensors rather than python lists ?
    - The data of a tensor is contiguous in memory, allowing fast computations

Tensors are generalization of matrices (which are 2d data-structures) to n-dimensionnal data structure.
Formally a 3d tensor $t$ of size $(n,m,t)$ is a familly of scalars that is indexed 3 integers $i,j,k$ : $t = ( t[i][j][k] )_{ 0\leq i<n, \quad 0\leq j<n , \quad  0\leq k<n }$.
So to access an element of $t$ you need to specify $3$ dimension (i,j,k) as well as you need to specify $2$ dimension to access an element of a matrix. We can generalize the définition to n-dimensionnal tensors.





<img src="img_tensors.png" alt="Description de l'image" width="400" height="300">

## Intialize, create a tensor

### From scratch

In which situation tensors are created from scratch ? For example, to test a program 
instead of processing real data you create your own, maybe random tensor. Tensors need to be initialized in neural networks, often randomly.

Few useful functions from torch:
- torch.zeros: 
    - Input: a size
    - Output: a tensor full of zeros
- torch.ones:
    - Input: a size
    - Output: a tensor full of ones
- torch.eye:
    - Input: 1 integer for a squared matrix, or 2 integers for a rectangular matrix
    - Output: a matrix with ones on the diagonal and zeros elsewere
- torch.rand:
    - Input: a size
    - Output: a tensor with scalars sampled uniformly at random in $[0,1]$
- torch.randn: 
    - Input: a size 
    - Output: a tensor with scalars sampled from the standard normal distribution

In [43]:
# Examples 

# One example for a matrix size 
size_mat = (3,3)
# One example for a 3d tensor 
size_3d_tensor = (2,3,3)

In [44]:
# Use of torch.zeros
print("torch.zeros:")
t = torch.zeros(size_mat)
print(t)
t = torch.zeros(size_3d_tensor)
print(t)

torch.zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [45]:
# Use of torch.ones 
print("torch.ones:")
t = torch.ones(size_mat)
print(t)
t = torch.ones(size_3d_tensor)
print(t)

torch.ones:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [46]:
# Use of torch.eye
print("torch.eye:")
t = torch.eye(3,8)
print(t)

torch.eye:
tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.]])


In [47]:
# Use of torch.rand
print("torch.rand:")
t = torch.rand(size_mat)
print(t)
t = torch.rand(size_3d_tensor)
print(t)

torch.rand:
tensor([[0.8839, 0.3826, 0.4673],
        [0.4336, 0.3027, 0.3050],
        [0.1909, 0.0944, 0.7962]])
tensor([[[0.2130, 0.3661, 0.9635],
         [0.0976, 0.6335, 0.4093],
         [0.4439, 0.9078, 0.7420]],

        [[0.2697, 0.2037, 0.4582],
         [0.9020, 0.4937, 0.7643],
         [0.6405, 0.9021, 0.9819]]])


In [48]:
# Use of torch.randn
print("torch.randn:")
t = torch.randn(size_mat)
print(t)
t = torch.randn(size_3d_tensor)
print(t)

torch.randn:
tensor([[ 0.1899,  0.3141,  1.7698],
        [-0.1104, -0.8260, -0.2686],
        [-0.0931, -0.1995, -0.3204]])
tensor([[[ 2.0434, -1.1787, -0.5447],
         [-0.2331,  1.0554, -0.0523],
         [ 0.1266, -0.0477, -0.4608]],

        [[-0.8478,  0.9271, -0.3248],
         [-0.2420,  0.5935, -0.2291],
         [-0.1701, -1.1707,  2.4336]]])


Some functions to create 1d tensors: 
- torch.linspace:
    - Input: a start, an end, and a step 
    - Output: Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive
- torch.arange:
    - Input: a start, an end, and a step 
    - Output: Creates a one-dimensional tensor with values start, start+step, +start + 2*step,... while start + k * step < end

In [49]:
# Example for linspace
print(torch.linspace(1,10,10))
print(torch.linspace(0.2,1.3,25))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([0.2000, 0.2458, 0.2917, 0.3375, 0.3833, 0.4292, 0.4750, 0.5208, 0.5667,
        0.6125, 0.6583, 0.7042, 0.7500, 0.7958, 0.8417, 0.8875, 0.9333, 0.9792,
        1.0250, 1.0708, 1.1167, 1.1625, 1.2083, 1.2542, 1.3000])


In [50]:
# Example for arange
print(torch.arange(1,10,1))
print(torch.arange(3,20,4))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 3,  7, 11, 15, 19])


### From existing data

In which situation should you convert a data structure into a tensor ? If you have some 
numpy arrays or python lists that you want to use a data train your neural network with torch, you will need to convert them into tensors.

For that we will use the function torch.tensor.

Which data structure can we convert into tensors with the function torch.tensor ? Some important ones :
- Python lists 
- Python scalars
- Numpy arrays
- Pandas dataframes

In [51]:
# From a Python list 
l = [1,2,3]
t = torch.tensor(l)
print("from a list:",t)

# From a matrix 
m = [[1,2,3],[4,5,6]]
t = torch.tensor(m)
print("from a matrix",t)

# From a Python scalar
x = 861 
t = torch.tensor(x)
print("from a scalar:",t)

# From a Numpy array
import numpy as np
arr = np.linspace(0,50,6)
t = torch.tensor(arr)
print("from a scalar:",t)

# You can also convert a tensor into a numpy array by doing t.numpy()

# # From a dataframe 
# import pandas as pd
# # We build a data set from a group of 2 grils and one boy
# features = ["boy","girl"]
# observations = [[0,1],[0,1],[1,0]]
# df = pd.DataFrame(observations,columns=features)
# print(df)
# t = torch.tensor(df)
# print("from a dataframe:",t)

from a list: tensor([1, 2, 3])
from a matrix tensor([[1, 2, 3],
        [4, 5, 6]])
from a scalar: tensor(861)
from a scalar: tensor([ 0., 10., 20., 30., 40., 50.], dtype=torch.float64)


Two ways of converting the type of the elements in a tensor : 
- torch.tensor(t,dtype=name_of_the_type): it **copies** t and converts the elements into the desired type
- torch.name_of_the_type() : it **copies** t and converts the elements into the desired type

In [52]:
# Example for torch.tensor(t,dtype=name_of_the_type)
t = torch.tensor([[1,2],[3,4]] , dtype=torch.float)
print(t.type())
t2 = torch.tensor(t,dtype=torch.long)
print(t2.type())
print("Are t and t2 the same in memory ? ",t.data_ptr() == t2.data_ptr())

torch.FloatTensor
torch.LongTensor
Are t and t2 the same in memory ?  False


/var/folders/rj/jncxshgs6tjb572dxm8jzvwc0000gn/T/ipykernel_51803/1658941027.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t2 = torch.tensor(t,dtype=torch.long)


In [53]:
# Example for torch.name_of_the_type()
t = torch.tensor([[1,2],[3,4]] , dtype=torch.float)
print(t.type())
t2 = t.long()
print(t2.type())
print("Are t and t2 the same in memory ? ",t.data_ptr() == t2.data_ptr())

torch.FloatTensor
torch.LongTensor
Are t and t2 the same in memory ?  False


## Operations on tensors

### Basic operations

Some common operations on tensors :
- Addition (elementwise):
    - Input: t, t' two tensors with equal size 
    - Output: t+t' 

- Multiplication by a scalar (elementwise):
    - Input: t a tensor, $a$ a scalar
    - Output: $a$*t where each element of t is multiplied by $a$

- Multiplication by a tensor (elementwise):
    - Input: t, t' two tensors with equal size 
    - Output: t*t' where each element of t is multiplied by $a$

- Multiplication of 2d tensors (matrix multiplication):
    - Input : t, t' two 2d tensors
    - Output : t @ t' the matrix multiplication of t and t'

In [54]:
# Examples
t = torch.ones((3,3))
print("t:",t)
print("t+t:",t+t)
print("12*t:",12*t)
t2 = torch.eye(3)
print("t2:",t2)
print("t*t2:",t*t2)
print("t@t2:",t@t2)

t: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t+t: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
12*t: tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])
t2: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
t*t2: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
t@t2: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### Functions on dimension

Some functions playing with dimensions :
- reshape:
    - Input: a tensor and a compatible size (the number of elements must be the same)
    - Output: a tensor with the new values as the source tensor but with the new size
- squeeze:
    - Input: a tensor, the index of the dimension of size 1 you want to squeeze
    - Output: the tensor with the dimension given removed
- unsqueeze:
    - Input: a tensor and the index at which to insert the singleton dimension
    - Output: returns a new tensor with a dimension of size one inserted at the specified position.
- unbind:
    - Input: a tensor
    - Output: Returns a tuple of all slices along a given dimension, already without it
- swapaxes:
    - Input: a tensor, axis1, and axis2
    - Output: Returns a tensor that is a transposed version of input. The given dimensions axis0 and axis1 are swapped
- cat: 
    - Input: a sequence of tensors and the index of the dimension along which you want to concatenate the tensors. All tensors must either have the same shape (except in the concatenating dimension) 
    - Output: Concatenates the given sequence of tensors in tensors in the given dimension. 

In [55]:
# Example for reshape
t = torch.tensor([[1,2,3],[4,5,6]])
print(t)
print(t.reshape((3,2)))
# As the number of elements must be the same we let torch inferre one dimension by leaving it at -1
print(t.reshape((3,-1)))
print(t.reshape((-1,)))
print(t.reshape(1,1,2,3))


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([1, 2, 3, 4, 5, 6])
tensor([[[[1, 2, 3],
          [4, 5, 6]]]])


In [56]:
# Example for squeeze
t = torch.tensor([[1,2,3,4,5]])
print(t)
print(t.size())

t2 = torch.squeeze(t,0)
print(t2)
print(t2.size())

print()

t = torch.tensor([[1],[2],[3],[4],[5]])
print(t)
print(t.size())

t2 = torch.squeeze(t,1)
print(t2)
print(t2.size())


tensor([[1, 2, 3, 4, 5]])
torch.Size([1, 5])
tensor([1, 2, 3, 4, 5])
torch.Size([5])

tensor([[1],
        [2],
        [3],
        [4],
        [5]])
torch.Size([5, 1])
tensor([1, 2, 3, 4, 5])
torch.Size([5])


In [57]:
# Example of unsqueeze
t = torch.tensor([1,2,3,4])
print(t)
print(torch.unsqueeze(t,0))
print(torch.unsqueeze(t,1))
# for example, it is used for adding a batch dimension as a first dimension : t.unsqueeze(0)

tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [58]:
# Example of unbind
t = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]]
                )
print(t)
print(torch.unbind(t,0))
print(torch.unbind(t,1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))
(tensor([1, 4, 7]), tensor([2, 5, 8]), tensor([3, 6, 9]))


In [59]:
# Example of swapaxes 
t = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]]
                )
print(t)
print(torch.swapaxes(t,0,1))
# An example of application:
# if you receiv a an image whith size (3,28,28) where 3 are the canals then to swap the canals 
# to the last dimension you can do torch.swapaxes(t,0,2) and otain a tensor of size (28,28,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [60]:
# Example for cat
t = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]]
                )
t2 = torch.tensor([[10,11,12],
                   [13,14,15],
                   [16,17,18]
                   ]
                )

# Concatenate the rows
print(torch.cat([t,t2],0))
# Concatenate the cols
print(torch.cat([t,t2],1))

# An example of application:
# Create a batch from a sequence of datapoints

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
tensor([[ 1,  2,  3, 10, 11, 12],
        [ 4,  5,  6, 13, 14, 15],
        [ 7,  8,  9, 16, 17, 18]])


### Reductions operations

Some functions extrating datas from tensors :
- sum:
    - Input: a tensor
    - Output: the sum of all scalars in the tensors
- mean:
    - Input: a tensor with float scalars
    - Output: the mean of the scalars in the tensor
- amax:
    - Input: a tensor, a dimension
    - Output: the maximum value of each slice of the input tensor in the given dimension

In [61]:
t = torch.tensor([[1,2],
                  [3,4]],dtype=torch.float)
print(t.sum())
print(t.mean())
# for each row we compute the max value
print(t.amax(1))
# for each col we compute the max value
print(t.amax(0))

tensor(10.)
tensor(2.5000)
tensor([2., 4.])
tensor([3., 4.])


### Math functions

Some important operations :
- allclose (used to test the equality between two tensors): 
    - Input: two tensors t1,t2 of same size 
    - Output: true if for all elements of t1 and t2 are close enough
- sign:
    - Input: a tensor
    - Ouput: for each element x , -1 if x<0 , 0 if x=0 , 1 if x>0

In [62]:
t1 = torch.zeros((3,3),dtype=torch.float)
t2 = torch.ones((3,3),dtype=torch.float)

# Example for allclose
print(torch.allclose(t1,t2))
print(torch.allclose(t1,t2/100000000))

# Example for sign 
t = torch.randn((3,3))
print(t)
print(torch.sign(t))

False
True
tensor([[ 0.4929, -1.3010, -2.9695],
        [ 2.5780, -0.6066,  0.7551],
        [ 1.3309, -0.8695, -0.8887]])
tensor([[ 1., -1., -1.],
        [ 1., -1.,  1.],
        [ 1., -1., -1.]])


## References
- https://pytorch.org/docs/stable/torch.html#tensors