In [4]:
import torch

# Exercices on Tensors

## Easy exercices

### Matrix multiplication

Code a function that take in input two Python matrices and return 
the multiplication of the two matrices in form of a tensor. You must convert those matrices into tensors 
and then using the @ operator to do the multiplication and return a tensor

### Matrix multiplication: Solution

In [5]:
def mult(A,B):
    t_A = torch.tensor(A)
    t_B = torch.tensor(B)
    return A @ B 

### Average of a 3d tensor

Implement a function that take an integer n in input and create a 3d tensor of dim (n,n,n) where its coefficients are sampled from the standard distribution, and finally return the average coefficient of the tensor by computing it yourself

### Average of a 3d tensor: Solution

In [6]:
def avg_3d(n):
    t = torch.randn((n,n,n))
    sum = .0
    for i in range(n):
        for j in range(n):
            for k in range(n):
                sum += t[i][j][k]
    return sum/(n*n*n)

## Concatenate rows
Sample two random n*n tensors from the uniform distribution on [0,1) and concatenate their rows into one tensor

## Concatenate rows : Solution

In [7]:
def cat_rows(n):
    t1 = torch.rand((n,n))
    t2 = torch.rand((n,n))
    return torch.cat([t1,t2],0)

## Medium exercices

### Convolution

Write a function taking a (n+2) * (n+2) tensor as an input, that outputs a n * n tensor which is the convolution of the first tensor : 
for all cases that are far enough from the borders, we compute the average of the 9 cases around.

### Convolution Solution

In [8]:
def convol(t):
    n = t.size(0)
    t_convol = torch.zeros((n-2,n-2),dtype=float)
    for i in range(1,n-1):
        for j in range(1,n-1):
        # We compute for each (i,j) that have enough neighbors, the mean of the neighboorhood 
            for l in range(i-1,i-1 + 3):
                for k in range(j-1,j-1 + 3):
                    t_convol[i-1][j-1] += t[l][k]
            t_convol[i-1][j-1] = t_convol[i-1][j-1]/9
    return t_convol

### Maximum of the rows
From a 2d tensor, using the function max, output a 1d tensor containing the maximum value of each row. 
For example [[1,2],[3,4],[1,2]] -> [2,4,2]

### Maximum of the rows: Solution

In [9]:
def max_of_rows(t):
    return t.max(1).values

### Match indices

From a n*n tensor t and a 2d tensor id of size n * 1 representing index of the col we want for each line, using gather function, output the 2d tensor 
[  [ t[0][id[0]] ] , [ t[1][id[1]] ] , ... , [ t[n-1][id[n-1]] ] ]

### Match indices: Solution

In [14]:
def match_indices(t,id):
    return t.gather(1,id)

tensor([[0.0485, 0.7651, 0.9479],
        [0.6339, 0.0483, 0.2329],
        [0.5675, 0.6988, 0.4671]])
tensor([[0, 1],
        [1, 2],
        [2, 0]])
tensor([[0.0485, 0.7651],
        [0.0483, 0.2329],
        [0.4671, 0.5675]])


### Modifying speficific indices

From a 2d tensor t , and a 2d boolean tensor b , if b[i][j] = True , shift t[i][j] by 1 and else do nothing. Do it using tensor indexing (you can find a guide [here](https://saturncloud.io/blog/pytorch-tensor-indexing-a-comprehensive-guide/#boolean-indexing))

In [18]:
def modifying_specific(t,b):
    t[b] = t[b]+1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])
